-- Keep automated link previews out of referral conversion reporting and retain
-- definitive finalize outcomes (including requests that arrive without a
-- referral token) for operational diagnosis.

alter table public.referral_clicks
  add column if not exists is_automated boolean not null default false;

comment on column public.referral_clicks.is_automated is
  'True for automated link previews/crawlers. Excluded from human referral funnel reporting.';

-- Backfill agents seen before referral-click began rejecting previews at the
-- edge. New automated requests are rejected before a click row is inserted.
update public.referral_clicks
set is_automated = true
where is_automated = false
  and coalesce(user_agent, '') ~* '(bot|crawler|spider|preview|facebookexternalhit|google-calendar-importer|google-lens|whatsapp/)';

create index if not exists referral_clicks_human_created_at_idx
  on public.referral_clicks (created_at desc)
  where is_automated = false;

create index if not exists referral_clicks_human_referrer_idx
  on public.referral_clicks (referrer_student_id, created_at desc)
  where is_automated = false;

create index if not exists referral_clicks_human_converted_at_idx
  on public.referral_clicks (converted_at desc)
  where is_automated = false and converted_at is not null;

create table if not exists public.referral_finalization_attempts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_id text null references public.students(id) on delete set null,
  referral_click_id uuid null references public.referral_clicks(id) on delete set null,
  platform text not null check (platform in ('android', 'ios', 'extension')),
  outcome text not null check (outcome in ('attributed', 'rejected')),
  reason text null,
  client_version text null
);

comment on table public.referral_finalization_attempts is
  'Definitive referral-finalize outcomes. Does not retain referral cookie values.';

create index if not exists referral_finalization_attempts_created_at_idx
  on public.referral_finalization_attempts (created_at desc);

create index if not exists referral_finalization_attempts_student_id_idx
  on public.referral_finalization_attempts (student_id)
  where student_id is not null;

create index if not exists referral_finalization_attempts_click_id_idx
  on public.referral_finalization_attempts (referral_click_id)
  where referral_click_id is not null;

alter table public.referral_finalization_attempts enable row level security;

drop policy if exists "referral_finalization_attempts_service_role"
  on public.referral_finalization_attempts;
create policy "referral_finalization_attempts_service_role"
  on public.referral_finalization_attempts for all
  to service_role
  using (true)
  with check (true);

-- Keep operational attempts for the same period as unconverted click data.
create or replace function public.cleanup_referral_and_profile_upload_data()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_clicks bigint;
  v_attempts bigint;
  v_failed bigint;
begin
  if auth.role() <> 'service_role' then raise exception 'Unauthorized'; end if;

  delete from public.referral_clicks
  where created_at < now() - interval '180 days'
    and converted_at is null;
  get diagnostics v_clicks = row_count;

  delete from public.referral_finalization_attempts
  where created_at < now() - interval '180 days';
  get diagnostics v_attempts = row_count;

  delete from public.profile_picture_submissions
  where status = 'failed' and updated_at < now() - interval '7 days';
  get diagnostics v_failed = row_count;

  return jsonb_build_object(
    'referralClicksDeleted', v_clicks,
    'referralAttemptsDeleted', v_attempts,
    'failedSubmissionsDeleted', v_failed
  );
end;
$$;

revoke all on function public.cleanup_referral_and_profile_upload_data()
  from public, anon, authenticated;
grant execute on function public.cleanup_referral_and_profile_upload_data()
  to service_role;
